"""user referrer

Revision ID: e4b7e8c165c1
Revises: bd9b36fc385a
Create Date: 2024-01-24 20:56:01.746272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e4b7e8c165c1'
down_revision: Union[str, None] = 'bd9b36fc385a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###
