name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: Build Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag image-bot:$(date +%s)
        docker build . --file admin/Dockerfile --tag image-admin:$(date +%s)
