name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! 👋 Thank you for opening your first issue. We appreciate your contribution! 🎉"
        pr-message: "Hi there! 👋 Congratulations on your first pull request! Your efforts make a difference! 🚀"
